# Generated by Django 2.1.3 on 2018-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='max_id',
            field=models.IntegerField(default=0),
        ),
    ]
