# Generated by Django 2.1.3 on 2018-12-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181211_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='pid',
        ),
    ]
