# Generated by Django 2.1.3 on 2018-12-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181216_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='abstract',
            new_name='body',
        ),
    ]
