# Generated by Django 2.1.3 on 2018-11-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
