# Generated by Django 2.1.3 on 2018-11-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181123_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='files',
            new_name='file',
        ),
    ]
